import json
import openai
import os

def generate_dynamic_html(json_data, api_key):
    """
    Generates dynamic HTML content from filtered smart home device data.
    """
    openai.api_key = api_key

    prompt = f"""
    You are tasked with creating a dynamic HTML page about smart home devices. Here's the filtered JSON data with news articles:
    {json.dumps(json_data, indent=4)}

    Create an HTML page with:
    - A header that says 'Latest Smart Home Device News'
    - A list of articles with their titles as clickable links, descriptions, and publication sources.
    - A responsive and mobile-friendly design using inline CSS.

    Output both the HTML and inline CSS.
    """

    try:
        response = openai.ChatCompletion.create(
            model="gpt-4",
            messages=[
                {"role": "system", "content": "You are a helpful assistant that generates HTML code."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_tokens=2000
        )
        return response.choices[0].message["content"]
    except openai.error.OpenAIError as e:
        print(f"OpenAI API Error: {e}")
        raise

if __name__ == "__main__":
    try:
        # Debugging: Confirm input file existence
        print("Attempting to read 'bundle_rss.json'")

        # Load the JSON data generated by the RSS script
        json_file_name = "bundle_rss.json"
        with open(json_file_name, "r") as json_file:
            json_data = json.load(json_file)
        print("JSON data loaded successfully.")

        # Retrieve the API key from the environment
        openai_api_key = os.getenv("OPENAI_API_KEY")
        if not openai_api_key:
            raise ValueError("OPENAI_API_KEY is not set in the environment.")

        # Generate the HTML
        print("Generating HTML...")
        try:
            dynamic_html = generate_dynamic_html(json_data, openai_api_key)
            with open("smart_home_news.html", "w") as html_file:
                html_file.write(dynamic_html)
            print("HTML file 'smart_home_news.html' created successfully.")
        except Exception as e:
            print(f"Error during HTML generation: {e}")
            raise

    except FileNotFoundError:
        print(f"Error: '{json_file_name}' not found. Ensure the RSS generation step completed successfully.")
        raise
    except ValueError as ve:
        print(f"Error: {ve}")
        raise
    except Exception as e:
        print(f"Unexpected error: {e}")
        raise
