name: RSS Generator Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate RSS Feed
        run: python website2rss.py

      - name: Verify Generated File
        run: |
          if [ ! -f bundle_rss.json ]; then
            echo "Error: bundle_rss.json not found."
            exit 1
          fi

      - name: Generate Dynamic HTML
        run: python generate_dynamic_html.py
        env:
          GEMMINI_FLASH_API_KEY: ${{ secrets.GEMMINI_FLASH_API_KEY }}

      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v3
        with:
          name: smart-home-news
          path: smart_home_news.html
          if-no-files-found: warn

      - name: Post to Blogger
        run: python post_to_blogger.py
        env:
          GEMMINI_FLASH_API_KEY: ${{ secrets.GEMMINI_FLASH_API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: secret.json

      - name: Verify Secret File Creation
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > secret.json
          ls -l secret.json
