name: Push HTML to Make.com Webhook

on:
  push:
    branches:
      - main

jobs:
  push_html:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: python -m pip install --upgrade pip requests beautifulsoup4

      # Step 4: Generate RSS JSON and HTML
      - name: Generate RSS and HTML
        run: python website2rss.py
        env:
          MAKE_COM_WEBHOOK_URL: ${{ secrets.MAKE_COM_WEBHOOK_URL }}

      # Step 5: Verify HTML file exists
      - name: Verify HTML file exists
        run: |
          if [ ! -f smart_home_news.html ]; then
            echo "Error: smart_home_news.html not found."
            exit 1
          fi

      # Step 6: Push HTML directly to Make.com webhook
      - name: Push HTML to Make.com HTTP module
        run: |
          curl -X POST \
            -H "Content-Type: text/html" \
            --data-binary @smart_home_news.html \
            "${{ secrets.MAKE_COM_HTML_WEBHOOK_URL }}"
