name: Website to RSS and HTML Generator

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the RSS generator
      - name: Generate RSS JSON
        run: python website2rss.py

      # Step 5: Generate Dynamic HTML and Post to Blogger
      - name: Generate Dynamic HTML and Post to Blogger
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BLOGGER_API_KEY: ${{ secrets.BLOGGER_API_KEY }}
        run: python generate_html.py

      # Step 6: Upload HTML artifact (optional for manual review)
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v3
        with:
          name: smart-home-news
          path: smart_home_news.html
