name: Generate and Post to Blogger

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Run every hour

jobs:
  generate-and-post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate HTML and Post to Blogger
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        BLOGGER_API_KEY: ${{ secrets.BLOGGER_API_KEY }}
      run: |
        python website2rss.py
        python generate_dynamic_html.py
        python post_to_blogger.py

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v3
      with:
        name: smart-home-news
        path: smart_home_news.html
