name: Generate and Post RSS

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step to create `secret.json` from the GitHub secret
    - name: Create secret.json file
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > secret.json
        ls -l secret.json # Verifying file creation
        echo "File content size:" $(wc -c < secret.json) # Print the file size (optional)

    # Run your Python scripts
    - name: Run website2rss.py
      run: python website2rss.py

    - name: Run generate_dynamic_html.py
      run: python generate_dynamic_html.py

    - name: Run post_to_blogger.py
      run: python post_to_blogger.py

    # Optionally upload generated files
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: smart-home-news
        path: smart_home_news.html
