name: Generate and Post to Blogger

on:
  push:
    branches:
      - main

jobs:
  generate_and_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create secret.json
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > secret.json
          python -m json.tool secret.json > temp.json && mv temp.json secret.json

      - name: Verify secret.json
        run: |
          if [ ! -f secret.json ]; then
            echo "Error: secret.json not created."
            exit 1
          fi
          echo "secret.json created successfully."

      - name: Generate Dynamic HTML
        run: python generate_dynamic_html.py

      - name: Verify Generated HTML
        run: |
          if [ ! -f smart_home_news.html ]; then
            echo "Error: smart_home_news.html not found."
            exit 1
          fi

      - name: Post to Blogger
        run: python post2blogger.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: secret.json
