name: Push RSS to Make.com Webhook

on:
  push:
    branches:
      - main

jobs:
  push_rss:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: python -m pip install --upgrade pip requests feedparser

      # Step 4: Run the website2rss script
      - name: Push RSS data to Make.com Webhook
        run: python website2rss.py
        env:
          MAKE_COM_WEBHOOK_URL: ${{ secrets.MAKE_COM_WEBHOOK_URL }}
